// Re-export database functions from @aidepedia/db
export {
  getArticleBySlug,
  getArticleById,
  listArticles,
  createArticle,
  updateArticle,
  deleteArticle,
  getCategories,
  getTags,
  getArticleTags,
  addTagToArticle,
  removeTagFromArticle,
  getArticlesByTag,
  getTagBySlug,
  createTag,
  getArticleRevisions,
  getRevisionById,
  revertToRevision,
  getEditorById,
  getReputationEvents,
  addReputationEvent,
  getEditorLeaderboard,
  updateEditorStats,
  // Draft functions
  getArticleDraft,
  saveArticleDraft,
  deleteArticleDraft,
  getUserDrafts,
} from '@aidepedia/db';

export type { 
  Article, 
  ArticleQueryParams, 
  PaginatedResult, 
  ArticleRevision,
  Editor,
  ReputationEvent,
  NewReputationEvent,
  Tag,
  NewTag,
  // Draft types
  ArticleDraft,
  NewArticleDraft,
  ArticleDraftWithArticle,
} from '@aidepedia/db';
